In [2]:
import numpy as np
x=np.array([1,2,3,4])
print(x,type(x))
print(x.shape,x.dtype)

[1 2 3 4] <class 'numpy.ndarray'>
(4,) int64


In [3]:
y=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(y,type(y))
print(y.dtype,y.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] <class 'numpy.ndarray'>
int64 (4, 3)


In [4]:
x=np.array(['Hello','World'])
print(x,x.dtype)

['Hello' 'World'] <U5


In [5]:
x=np.array([1,2,'World'])
print(x,x.dtype)

['1' '2' 'World'] <U21


In [6]:
x=np.array([1,2.5,4])
print(x,x.dtype)

[1.  2.5 4. ] float64


In [7]:
x=np.array([1.4,3.5,5.6],dtype=np.int64)
print(x,x.dtype)

[1 3 5] int64


In [8]:
y=np.arange(25).reshape(5,5)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [9]:
print(y[y>20])

[21 22 23 24]


In [10]:
print(y[y<10])

[0 1 2 3 4 5 6 7 8 9]


In [11]:
print(y[(y>17) & (y<23)])

[18 19 20 21 22]


In [12]:
y[(y>17) & (y<23)]=-1
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 -1 -1]
 [-1 -1 -1 23 24]]


In [13]:
x=np.array([1,2,3,4,5])
y=np.array([6,7,2,8,4])

print(np.intersect1d(x,y))
print(np.setdiff1d(x,y))
print(np.union1d(x,y))

[2 4]
[1 3 5]
[1 2 3 4 5 6 7 8]


In [14]:
x=np.random.randint(1,11,size=(10,))
print(x)

[ 3  3  6  2  9  8  7 10  9  5]


In [15]:
print(np.sort(x))
print(x)

[ 2  3  3  5  6  7  8  9  9 10]
[ 3  3  6  2  9  8  7 10  9  5]


In [16]:
print(np.sort(np.unique(x)))

[ 2  3  5  6  7  8  9 10]


In [17]:
x.sort()
print(x)

[ 2  3  3  5  6  7  8  9  9 10]


In [18]:
x=np.random.randint(1,11,size=(5,5))
print(x)

[[ 7  1  6  3  2]
 [ 2  8  6  6  5]
 [ 8  1  3  9 10]
 [ 6  7  8  1  8]
 [ 9  5  1  5  8]]


In [19]:
print(np.sort(x,axis=1)) # sort by columns

[[ 1  2  3  6  7]
 [ 2  5  6  6  8]
 [ 1  3  8  9 10]
 [ 1  6  7  8  8]
 [ 1  5  5  8  9]]


In [20]:
print(np.sort(x,axis=0)) #sort by rows

[[ 2  1  1  1  2]
 [ 6  1  3  3  5]
 [ 7  5  6  5  8]
 [ 8  7  6  6  8]
 [ 9  8  8  9 10]]


In [21]:
x=np.zeros((3,4),dtype=int)
print(x)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [22]:
x=np.ones((3,4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [23]:
x=np.full((4,3),5)
print(x)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [24]:
x=np.eye(5,dtype=int)
print(x)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [25]:
x=np.diag([10,20,30,40])
print(x)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


In [26]:
x=np.arange(10)
print(x)
x=np.arange(1,10)
print(x)
x=np.arange(1,14,3)
print(x)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[ 1  4  7 10 13]


In [27]:
x=np.linspace(0,25,10)
print(x)
x=np.linspace(0,25,10,endpoint=False)
print(x)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]
[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


In [28]:
x=np.arange(20)
print(x)
x=np.reshape(x,(4,5))
print(x)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [29]:
x=np.random.randint(0,11,(3,2))
print(x)

[[7 8]
 [8 8]
 [3 2]]


In [30]:
x=np.random.normal(0,0.1,size=(1000,1000))
print(x)

[[-0.13197562 -0.01825498  0.10451512 ... -0.00930931  0.1160343
   0.08400294]
 [-0.10242643  0.03946827  0.04702298 ... -0.03244239 -0.10156951
   0.15084532]
 [-0.07152234  0.02370499 -0.14525631 ...  0.05545588  0.0911025
  -0.09707202]
 ...
 [ 0.10763416  0.02597116 -0.06021001 ...  0.01957839  0.00952
   0.1074399 ]
 [ 0.03968552  0.05477714 -0.01265608 ... -0.17495554 -0.10461035
  -0.02083848]
 [-0.03887372  0.17561809 -0.13534345 ... -0.04593158  0.06889054
   0.01432895]]


In [31]:
x=np.r_[1:5,7,10,14:24]
print(x)
x=np.repeat("hello",10)
print(x)
x=np.repeat(4,10)
print(x)

[ 1  2  3  4  7 10 14 15 16 17 18 19 20 21 22 23]
['hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello'
 'hello']
[4 4 4 4 4 4 4 4 4 4]


In [32]:
x=np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [33]:
print('1st element:',x[0])
print('2nd element:',x[1])
print('5th element:',x[4])

1st element: 1
2nd element: 2
5th element: 5


In [34]:
print('1st element:',x[-5])
print('2nd element:',x[-4])
print('5th element:',x[-1])

x[3]=20
print(x)

1st element: 1
2nd element: 2
5th element: 5
[ 1  2  3 20  5]


In [35]:
x=np.arange(1,10).reshape(3,3)
print(x)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
print('element at (0,0):',x[0,0])
print('element at (0,1):',x[0,1])
print('element at (2,2):',x[2,2])

x[0,0]=20
print(x)

element at (0,0): 1
element at (0,1): 2
element at (2,2): 9
[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [37]:
x=np.array([1,2,3,4,5])
print(x)
x=np.delete(x,[0,4])
print(x)

[1 2 3 4 5]
[2 3 4]


In [38]:
y=np.arange(1,10).reshape(3,3)
print(y)

w=np.delete(y,0,axis=0)
print('\n',w)

z=np.delete(y,[0,2],axis=1)
print('\n',z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[4 5 6]
 [7 8 9]]

 [[2]
 [5]
 [8]]


In [39]:
x=np.array([1,2,3,4,5])
print(x)
x=np.append(x,6)
print(x)
x=np.append(x,[7,8])
print(x)

[1 2 3 4 5]
[1 2 3 4 5 6]
[1 2 3 4 5 6 7 8]


In [40]:
y=np.arange(1,10).reshape(3,3)
print(y)
w=np.append(y,[[10,11,12]],axis=0)
print(w)
v=np.append(y,[[10],[11],[12]],axis=1)
print(v)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [41]:
x=np.array([1,2,5,6,7])
print(x)

[1 2 5 6 7]


In [42]:
x=np.insert(x,2,[3,4])
print(x)

[1 2 3 4 5 6 7]


In [43]:
y=np.array([[1,2,3],[7,8,9]])
print(y)

w=np.insert(y,1,[4,5,6],axis=0)
print(w)

v=np.insert(y,1,5,axis=1)
print(v)

[[1 2 3]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 5 2 3]
 [7 5 8 9]]


In [44]:
x=np.array([1,2])
print(x)
y=np.array([[3,4],[5,6]])
print(y)
z=np.vstack((x,y))
print(z)
w=np.hstack((y,x.reshape(2,1)))
print(w)

[1 2]
[[3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[3 4 1]
 [5 6 2]]


In [45]:
x=np.arange(1,21).reshape(4,5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [46]:
w=x[1:4,2:5]
print(w)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [47]:
y=x[1:,2:]
print(y)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [48]:
v=x[:3,2:]
print(v)

[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


In [49]:
z=x[:,2]
print(z)

[ 3  8 13 18]


In [50]:
z=x[:,2]
print(z)

[ 3  8 13 18]


In [51]:
z=x[:,2:3]
print(z)

[[ 3]
 [ 8]
 [13]
 [18]]


In [52]:
z=x[1:,2:]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [53]:
z[2,2]=555
print(x) #shallow copy of x is z , if we make changes to z .. x changes too

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19 555]]


In [54]:
x=np.arange(1,21).reshape(4,5)
z=x[1:,2:].copy()
z[2,2]=1000
print(z)
print(x)

[[   8    9   10]
 [  13   14   15]
 [  18   19 1000]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [55]:
indices=np.array([1,3])
print(indices)
print(x[indices,:])
print(x[:,indices])

[1 3]
[[ 6  7  8  9 10]
 [16 17 18 19 20]]
[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]]


In [56]:
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [57]:
z=np.diag(x)
print(z)

[ 1  7 13 19]


In [60]:
z=np.diag(x,k=1)
print(z)

[ 2  8 14 20]


In [126]:
z=np.diag(x,k=-1)
print(z)

[ 6 12 18]


In [129]:
x=np.array([[1,2,3],[5,2,8],[1,2,3]])
print(x)
print(np.unique(x))

[[1 2 3]
 [5 2 8]
 [1 2 3]]
[1 2 3 5 8]


In [130]:
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
print(x)
print(y)

[1 2 3 4]
[5 6 7 8]


In [132]:
print(x+y)
print(np.add(x,y))

[ 6  8 10 12]
[ 6  8 10 12]


In [134]:
print(x-y)
print(np.subtract(x,y))
print(x*y)
print(np.multiply(x,y))
print(x/y)
print(np.divide(x,y))

[-4 -4 -4 -4]
[-4 -4 -4 -4]
[ 5 12 21 32]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[0.2        0.33333333 0.42857143 0.5       ]


In [135]:
# We create two rank 2 ndarrays
X = np.array([1,2,3,4]).reshape(2,2)
Y = np.array([5.5,6.5,7.5,8.5]).reshape(2,2)

# We print X
print()
print('X = \n', X)

# We print Y
print()
print('Y = \n', Y)
print()

# We perform basic element-wise operations using arithmetic symbols and functions
print('X + Y = \n', X + Y)
print()
print('add(X,Y) = \n', np.add(X,Y))
print()
print('X - Y = \n', X - Y)
print()
print('subtract(X,Y) = \n', np.subtract(X,Y))
print()
print('X * Y = \n', X * Y)
print()
print('multiply(X,Y) = \n', np.multiply(X,Y))
print()
print('X / Y = \n', X / Y)
print()
print('divide(X,Y) = \n', np.divide(X,Y))


X = 
 [[1 2]
 [3 4]]

Y = 
 [[5.5 6.5]
 [7.5 8.5]]

X + Y = 
 [[ 6.5  8.5]
 [10.5 12.5]]

add(X,Y) = 
 [[ 6.5  8.5]
 [10.5 12.5]]

X - Y = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]

subtract(X,Y) = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]

X * Y = 
 [[ 5.5 13. ]
 [22.5 34. ]]

multiply(X,Y) = 
 [[ 5.5 13. ]
 [22.5 34. ]]

X / Y = 
 [[0.18181818 0.30769231]
 [0.4        0.47058824]]

divide(X,Y) = 
 [[0.18181818 0.30769231]
 [0.4        0.47058824]]


In [140]:
print(x)
print(np.sqrt(x))
print(np.power(x,2))


[1 2 3 4]
[1.         1.41421356 1.73205081 2.        ]
[ 1  4  9 16]


In [143]:
x=np.array([[1,2],[3,4]])
print(x)
print(x.mean())
print(x.mean(axis=1))
print(x.mean(axis=0))

[[1 2]
 [3 4]]
2.5
[1.5 3.5]
[2. 3.]


In [145]:
print(x.sum())
print(x.sum(axis=0))
print(x.sum(axis=1))

10
[4 6]
[3 7]


In [147]:
print(x.std())  #standard deviation of x
print(np.median(x))  #median of x
print(x.max()) #max element in x
print(x.min()) # min element in x

1.118033988749895
2.5
4
1


In [149]:
print(x)
print(x+3)
print(x-3)
print(x*3)
print(x/7)

[[1 2]
 [3 4]]
[[4 5]
 [6 7]]
[[-2 -1]
 [ 0  1]]
[[ 3  6]
 [ 9 12]]
[[0.14285714 0.28571429]
 [0.42857143 0.57142857]]


In [156]:
y=np.arange(9).reshape(3,3)
x=np.arange(3)
z=np.arange(3).reshape(3,1)
print(y)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]


In [155]:
print(y+x)

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


In [158]:
print(z+y)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]
